apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-cinema-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projet-cinema
  template:
    metadata:
      labels:
        app: projet-cinema
    spec:
      containers:
      - name: projet-cinema
        image: omarelhedfi/projet_cinema:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: projet-cinema-service
spec:
  type: NodePort
  selector:
    app: projet-cinema
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
