apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-cinema-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: projet-cinema
  template:
    metadata:
      labels:
        app: projet-cinema
    spec:
      containers:
      - name: projet-cinema
        image: omarelhedfi/projet_cinema:latest  # La version sera remplacée par sed dans le pipeline
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: projet-cinema-service
spec:
  selector:
    app: projet-cinema
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30008  # Exposé pour accès via Minikube

