apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-cinema-deployment
  labels:
    app: projet-cinema
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: projet-cinema
  template:
    metadata:
      labels:
        app: projet-cinema
    spec:
      containers:
      - name: projet-cinema
        image: omarelhedfi/projet_cinema:1.0.60 
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SERVER_PORT
          value: "8082"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 90  
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: projet-cinema-service
spec:
  type: NodePort
  selector:
    app: projet-cinema
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30008
